from plotter import Plotter

from lsystem_to_hpgl import convert_lsystem_to_hpgl

path = "F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+ffffff-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFffffff+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-ffffff+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFffffff-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+ffffff-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFffffff+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-ffffff+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFffffff-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+ffffff-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFffffff+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-ffffff+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFffffff-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+ffffff-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFffffff+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-ffffff+F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFffffff-F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFFF+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF"

cmds = convert_lsystem_to_hpgl(path, 60, 6500, 4700)

p = Plotter()

p.exec_hpgl(cmds)
